s3rius/FastAPI-template

- fastapi_template/template/{{cookiecutter.project_name}}/.gitlab-ci.yml
- fastapi_template/template/{{cookiecutter.project_name}}/deploy/Dockerfile
- fastapi_template/template/{{cookiecutter.project_name}}/deploy/docker-compose.yml
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/settings.py
- pyproject.toml
> Fixed SQLITE support.

- fastapi_template/cli.py
- fastapi_template/input_model.py
- fastapi_template/template/cookiecutter.json
- fastapi_template/template/hooks/pre_gen_project.py
- fastapi_template/template/{{cookiecutter.project_name}}/.dockerignore
- fastapi_template/template/{{cookiecutter.project_name}}/.gitlab-ci.yml
- fastapi_template/template/{{cookiecutter.project_name}}/conditional_files.json
- fastapi_template/template/{{cookiecutter.project_name}}/deploy/docker-compose.yml
- fastapi_template/template/{{cookiecutter.project_name}}/deploy/kube/app.yml
- fastapi_template/template/{{cookiecutter.project_name}}/deploy/kube/db.yml
- fastapi_template/template/{{cookiecutter.project_name}}/deploy/kube/redis.yml
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/db/migrations/env.py
> Updated kubernetes config.

- README.md
- fastapi_template/cli.py
- fastapi_template/input_model.py
- fastapi_template/template/cookiecutter.json
- fastapi_template/template/{{cookiecutter.project_name}}/conditional_files.json
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/web/api/router.py
- pyproject.toml
Description:
* Added swotchable routers.
* Dummy model generation can be skipped.
* Fixed cli '--help' output.
> Updated template.

- fastapi_template/template/hooks/post_gen_project.py
- pyproject.toml
> Fixed resource cleanup.

- fastapi_template/template/{{cookiecutter.project_name}}/deploy/docker-compose.yml
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/conftest.py
- pyproject.toml
Description:
* Fixed health command.
* Fixed initialize_db for tortoise fixture in conftest.
Closes #22.
> Fixed postgres healthcheck

- fastapi_template/template/{{cookiecutter.project_name}}/.pre-commit-config.yaml
- fastapi_template/template/{{cookiecutter.project_name}}/deploy/Dockerfile
- fastapi_template/template/{{cookiecutter.project_name}}/deploy/docker-compose.yml
- fastapi_template/template/{{cookiecutter.project_name}}/deploy/kube/app.yml
- fastapi_template/template/{{cookiecutter.project_name}}/deploy/kube/db.yml
- fastapi_template/template/{{cookiecutter.project_name}}/deploy/kube/namespace.yml
- fastapi_template/template/{{cookiecutter.project_name}}/deploy/kube/redis.yml
- pyproject.toml
Closes #25. 
Signed-off-by: Pavel <win10@list.ru>
> Fixed k8s configs.

- fastapi_template/input_model.py
Rebased version of a request #55 by @sorasful.
> Renamed input_models 'gitlab' to 'gitlab_ci' (#54)

- .github/workflows/test.yml
I think it would be a good idea to run the tests on pull requests.
> add continuous integration for pull requests

- README.md
- fastapi_template/cli.py
Fix 2 typos
@s3rius 
```
--routers             Add exmaple routers
--swagger             Eanble self-hosted swagger
```
> Fix typos in README.md

- fastapi_template/cli.py
- fastapi_template/input_model.py
- fastapi_template/template/{{cookiecutter.project_name}}/conditional_files.json
- fastapi_template/template/{{cookiecutter.project_name}}/pyproject.toml
- fastapi_template/template/{{cookiecutter.project_name}}/replaceable_files.json
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/conftest.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/db_psycopg/dao/dummy_dao.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/db_psycopg/dependencies.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/db_psycopg/models/dummy_model.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/tests/test_dummy.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/web/lifetime.py
- fastapi_template/tests/test_generator.py
> Added psycopg support.

- fastapi_template/template/{{cookiecutter.project_name}}/README.md
- fastapi_template/template/{{cookiecutter.project_name}}/deploy/docker-compose.dev.yml
> Added docker-compose for local development.

- .github/workflows/test.yml
- fastapi_template/input_model.py
- fastapi_template/template/{{cookiecutter.project_name}}/deploy/docker-compose.dev.yml
- fastapi_template/template/{{cookiecutter.project_name}}/deploy/docker-compose.yml
- fastapi_template/tests/conftest.py
- poetry.lock
- pyproject.toml
This improvement includes bumping docker-compose version and updating mysql container environment variables.
> Added pytest-xdist to speedup tests 

- .github/workflows/test.yml
- fastapi_template/input_model.py
- fastapi_template/template/{{cookiecutter.project_name}}/README.md
- fastapi_template/template/{{cookiecutter.project_name}}/conditional_files.json
- fastapi_template/template/{{cookiecutter.project_name}}/deploy/docker-compose.yml
- fastapi_template/template/{{cookiecutter.project_name}}/deploy/kube/db.yml
- fastapi_template/template/{{cookiecutter.project_name}}/pyproject.toml
- fastapi_template/template/{{cookiecutter.project_name}}/replaceable_files.json
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/__main__.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/conftest.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/db_piccolo/app_conf.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/db_piccolo/dao/__init__.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/db_piccolo/dao/dummy_dao.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/db_piccolo/migrations/2022-04-16T17-38-51-672827.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/db_piccolo/models/__init__.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/db_piccolo/models/dummy_model.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/piccolo_conf.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/tests/test_dummy.py
- fastapi_template/tests/test_generator.py
> Added piccolo integration.

- fastapi_template/template/{{cookiecutter.project_name}}/conditional_files.json
> Fixed extra features files.

- fastapi_template/cli.py
- fastapi_template/input_model.py
- fastapi_template/template/cookiecutter.json
- fastapi_template/template/{{cookiecutter.project_name}}/.flake8
- fastapi_template/template/{{cookiecutter.project_name}}/conditional_files.json
- fastapi_template/template/{{cookiecutter.project_name}}/deploy/docker-compose.yml
- fastapi_template/template/{{cookiecutter.project_name}}/deploy/kube/app.yml
- fastapi_template/template/{{cookiecutter.project_name}}/deploy/kube/rabbit.yml
- fastapi_template/template/{{cookiecutter.project_name}}/deploy/kube/redis.yml
- fastapi_template/template/{{cookiecutter.project_name}}/pyproject.toml
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/conftest.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/services/rabbit/__init__.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/services/rabbit/dependencies.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/services/rabbit/lifetime.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/services/redis/__init__.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/services/redis/lifetime.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/settings.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/tests/test_rabbit.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/web/api/rabbit/__init__.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/web/api/rabbit/schema.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/web/api/rabbit/views.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/web/api/router.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/web/application.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/web/gql/context.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/web/gql/rabbit/__init__.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/web/gql/rabbit/mutation.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/web/gql/rabbit/schema.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/web/gql/router.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/web/lifetime.py
- fastapi_template/tests/test_generator.py
> Added RabbitMQ service.

- fastapi_template/template/{{cookiecutter.project_name}}/pyproject.toml
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/services/redis/dependency.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/services/redis/lifetime.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/tests/test_dummy.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/tests/test_echo.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/tests/test_rabbit.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/tests/test_redis.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/web/api/redis/views.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/web/gql/context.py
Description:
This commit changes aioredis dependency to redis.
Since aioredis now merged in official redis library.
Also after bumping straweberry-graphql I foundout that
they changed name of endpoint I used in tests. I fixed it.
> Redis and Straweberry updates.

- README.md
- fastapi_template/template/{{cookiecutter.project_name}}/.pre-commit-config.yaml
- fastapi_template/template/{{cookiecutter.project_name}}/README.md
- fastapi_template/template/{{cookiecutter.project_name}}/deploy/docker-compose.dev.yml
- fastapi_template/template/{{cookiecutter.project_name}}/deploy/docker-compose.otlp.yml
- fastapi_template/template/{{cookiecutter.project_name}}/deploy/otel-collector-config.yml
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/settings.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/web/api/dummy/views.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/web/api/echo/views.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/web/api/rabbit/views.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/web/application.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/web/gql/dummy/query.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/web/gql/rabbit/mutation.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/web/gql/redis/mutation.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/web/gql/redis/query.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/web/gql/redis/schema.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/web/lifetime.py
> Updated generated documentation.

- fastapi_template/cli.py
- fastapi_template/input_model.py
- fastapi_template/template/cookiecutter.json
- fastapi_template/template/{{cookiecutter.project_name}}/conditional_files.json
- fastapi_template/template/{{cookiecutter.project_name}}/pyproject.toml
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/__main__.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/logging.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/settings.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/web/application.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/web/lifetime.py
- fastapi_template/tests/test_generator.py
> Added loguru logger.

- README.md
- fastapi_template/cli.py
- fastapi_template/input_model.py
- fastapi_template/template/cookiecutter.json
- fastapi_template/template/{{cookiecutter.project_name}}/deploy/docker-compose.yml
> Added optional traefik labeling.

- .github/workflows/test.yml
- Dockerfile
- README.md
- fastapi_template/template/{{cookiecutter.project_name}}/.gitlab-ci.yml
- fastapi_template/template/{{cookiecutter.project_name}}/deploy/Dockerfile
I think it will be better to use actual version of poetry.
> Set poetry version to 1.1.13

- fastapi_template/cli.py
- fastapi_template/input_model.py
- fastapi_template/template/cookiecutter.json
- fastapi_template/template/{{cookiecutter.project_name}}/.github/workflows/tests.yml
- fastapi_template/template/{{cookiecutter.project_name}}/.gitlab-ci.yml
- fastapi_template/template/{{cookiecutter.project_name}}/conditional_files.json
- fastapi_template/template/{{cookiecutter.project_name}}/deploy/docker-compose.yml
- fastapi_template/template/{{cookiecutter.project_name}}/pyproject.toml
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/conftest.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/logging.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/services/kafka/__init__.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/services/kafka/dependencies.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/services/kafka/lifetime.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/services/rabbit/dependencies.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/services/rabbit/lifetime.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/services/redis/dependency.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/services/redis/lifetime.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/settings.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/tests/test_kafka.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/web/api/kafka/__init__.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/web/api/kafka/schema.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/web/api/kafka/views.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/web/api/router.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/web/gql/context.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/web/gql/kafka/__init__.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/web/gql/kafka/mutation.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/web/gql/kafka/schema.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/web/gql/router.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/web/lifetime.py
- fastapi_template/tests/test_generator.py
> Added kafka integration.

- fastapi_template/input_model.py
- fastapi_template/template/{{cookiecutter.project_name}}/.github/workflows/tests.yml
> Fixed pytest action for MYSQL. Bumped MYSQL and postgresql versions.

- fastapi_template/template/{{cookiecutter.project_name}}/.flake8
- fastapi_template/template/{{cookiecutter.project_name}}/pyproject.toml
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/web/application.py
- poetry.lock
- pyproject.toml
- scripts/version_bumper.py
> Dependencies updated.

- .github/workflows/test.yml
- Dockerfile
- fastapi_template/template/{{cookiecutter.project_name}}/.gitlab-ci.yml
- fastapi_template/template/{{cookiecutter.project_name}}/deploy/Dockerfile
> Poetry version bumped to 1.2.2. Closes #131.

- fastapi_template/template/{{cookiecutter.project_name}}/README.md
- fastapi_template/template/{{cookiecutter.project_name}}/pyproject.toml
there was a minor typo in the project template README.md.
> Readme typo

- fastapi_template/input_model.py
This PR fixes windows support. Closes #142.
Actually it adds older menus if new are not available.
> Fixed windows support.

- fastapi_template/template/{{cookiecutter.project_name}}/pyproject.toml
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/conftest.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/db_sa/base.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/db_sa/dao/dummy_dao.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/db_sa/models/dummy_model.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/web/lifetime.py
- poetry.lock
> Updated dependencies.

- fastapi_template/cli.py
- fastapi_template/template/cookiecutter.json
- fastapi_template/template/{{cookiecutter.project_name}}/conditional_files.json
- fastapi_template/template/{{cookiecutter.project_name}}/deploy/docker-compose.dev.yml
- fastapi_template/template/{{cookiecutter.project_name}}/deploy/docker-compose.yml
- fastapi_template/template/{{cookiecutter.project_name}}/pyproject.toml
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/db_psycopg/dependencies.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/db_sa/dependencies.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/logging.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/services/kafka/dependencies.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/services/rabbit/dependencies.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/services/redis/dependency.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/taskiq.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/web/lifetime.py
- fastapi_template/tests/conftest.py
- fastapi_template/tests/test_generator.py
This request adds taskiq support for fastapi-template. 
This PR closes #106.
> Added initial taskiq support

- fastapi_template/__main__.py
- fastapi_template/cli.py
This PR adds required programs check before running the generator. 
Closes #153.
> Added requirements check before startup

- fastapi_template/template/{{cookiecutter.project_name}}/.gitignore
- fastapi_template/template/{{cookiecutter.project_name}}/conditional_files.json
- fastapi_template/template/{{cookiecutter.project_name}}/deploy/docker-compose.yml
- fastapi_template/template/{{cookiecutter.project_name}}/pyproject.toml
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/tkq.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/web/lifetime.py
- fastapi_template/tests/utils.py
Various fixed for taskiq integration.
> Fixed taskiq.

- .github/workflows/test.yml
- Dockerfile
- fastapi_template/template/{{cookiecutter.project_name}}/.gitlab-ci.yml
- fastapi_template/template/{{cookiecutter.project_name}}/README.md
- fastapi_template/template/{{cookiecutter.project_name}}/deploy/Dockerfile
- fastapi_template/template/{{cookiecutter.project_name}}/deploy/docker-compose.dev.yml
- fastapi_template/template/{{cookiecutter.project_name}}/deploy/docker-compose.yml
- fastapi_template/tests/utils.py
> Optimized image size

- fastapi_template/template/{{cookiecutter.project_name}}/README.md
opentelemetry / Opentelemetry -> OpenTelemetry
possibe -> possible
> Fix typos & capitalizations

- fastapi_template/cli.py
- fastapi_template/template/cookiecutter.json
- fastapi_template/template/{{cookiecutter.project_name}}/.pre-commit-config.yaml
- fastapi_template/template/{{cookiecutter.project_name}}/conditional_files.json
- fastapi_template/template/{{cookiecutter.project_name}}/pyproject.toml
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/__main__.py
- fastapi_template/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/gunicorn_runner.py
- fastapi_template/tests/test_generator.py
> Added gunicorn support

- pyproject.toml
Removing unused dependency 'typer'.
> Removing unused dependency.
